# This file is used so if configuration change needs to applied remotely, 
# in the case that something breaks badly, it can be done through this file
Sim:
  MsFs:
    ExcludePaths:
    - asobo-aircraft*
    - asobo-bushtrip*
    - asobo-cameras
    - asobo-flight*
    - asobo-freeflights
    - asobo-jetways
    - asobo-landingchallenge*
    - asobo-liveevent
    - asobo-material-lib
    - asobo-modellib*
    - asobo-scenarii
    - asobo-services
    - asobo-simobjects*
    - asobo-vcockpits*
    - asobo-vliveries
    - bf-pgg
    - bf-texture-synth-lib
    - fs-base-achievements
    - fs-base-ai-traffic
    - fs-base-aircraft*
    - fs-base-cgl
    - fs-base-effects
    - fs-base-ingamepanels*
    - fs-base-marketplace
    - fs-base-material-lib
    - fs-base-soundbanks
    - fs-base-ui-pages
    - fs-base-videos
    - microsoft-aircraft-*
    - navigraph-*
    - pc-fs-base-bigfiles
    - aig-aitraffic-oci-beta
    - Bijan Current Season
    - Bijan Model Assets
    - lvfr-airport-jetway-pro
    - lvfr-arex-ap
    - lvfr-arex-europe
    - lvfr-arex-middleeastafrica
    - lvfr-arex-na
    - lvfr-arex-southamericatropics
    - fsdreamteam-gsx-*
    ExcludeFiles:
    - shape*.bgl
    - dem4km.bgl
    - lclookup.bgl
    - magdec.bgl
    - PopulationDensity.bgl
    - regions.bgl
    - seasons.bgl
    - worldlc.bgl
    - worldwc.bgl
    - timezone.bgl
    - AIRACCycle.bgl
    - Boundaries*.bgl
